// Goal 10 (B-004): the SDK's hand-written response types must conform to the contracts published
// in the OpenAPI document (`src/generated/openapi.ts`, generated by `pnpm --filter @kora/sdk
// gen:types`). The checks are compile-time: `pnpm typecheck` fails when an SDK type drifts from
// the contract (a field the contract requires is missing or has an incompatible type).
import { describe, expect, it } from 'vitest';

import type { paths } from './generated/openapi.js';
import type {
  AccountView,
  AuditListResponse,
  AuditVerifyResponse,
  CandlesResponse,
  HealthResponse,
  InstrumentDetail,
  KillSwitchResponse,
  KillSwitchState,
  LoginResponse,
  MarketStatusResponse,
  MeResponse,
  OrderDetail,
  OrderDto,
  PlaceOrderResponse,
  PositionDto,
  FillDto,
  PreviewResponse,
  QuestionnaireResponse,
  QuotesResponse,
} from './types.js';

type Json<P extends keyof paths, M extends keyof paths[P], S extends number> = paths[P][M] extends {
  responses: { [K in S]: { content: { 'application/json': infer T } } };
}
  ? T
  : never;

type KnownKeys<T> = keyof { [K in keyof T as string extends K ? never : number extends K ? never : K]: T[K] };
type Primitive = string | number | boolean | null | undefined;

/**
 * true when the SDK type S provides every field the contract G requires, recursively, and each
 * leaf type is compatible (one assignable to the other: the SDK may narrow a string to a literal or
 * template type such as `robot:${string}`, but a string can never become a number).
 */
type Conforms<S, G> = [G] extends [never]
  ? false
  : [G] extends [Primitive]
    ? [G] extends [S]
      ? true
      : [S] extends [G]
        ? true
        : false
    : G extends ReadonlyArray<infer GE>
      ? S extends ReadonlyArray<infer SE>
        ? Conforms<SE, GE>
        : false
      : unknown extends G
        ? true
        : G extends object
          ? S extends object
            ? false extends { [K in KnownKeys<G>]-?: undefined extends G[K] ? true : K extends keyof S ? Conforms<NonNullable<S[K]>, NonNullable<G[K]>> : false }[KnownKeys<G>]
              ? false
              : true
            : false
          : [G] extends [S]
            ? true
            : [S] extends [G]
              ? true
              : false;

type Assert<T extends true> = T;

// One line per contract the SDK types. A `false` here is a compile error.
export type ContractChecks = [
  Assert<Conforms<HealthResponse, Json<'/health', 'get', 200>>>,
  Assert<Conforms<Extract<LoginResponse, { status: 'ok' }>, Extract<Json<'/auth/login', 'post', 200>, { status: 'ok' }>>>,
  Assert<Conforms<MeResponse, Json<'/me', 'get', 200>>>,
  Assert<Conforms<AuditListResponse, Json<'/audit', 'get', 200>>>,
  Assert<Conforms<AuditVerifyResponse, Json<'/audit/verify', 'get', 200>>>,
  Assert<Conforms<InstrumentDetail, Json<'/instruments/{symbol}', 'get', 200>>>,
  Assert<Conforms<CandlesResponse, Json<'/candles', 'get', 200>>>,
  Assert<Conforms<QuotesResponse, Json<'/quotes', 'get', 200>>>,
  Assert<Conforms<MarketStatusResponse, Json<'/market-data/status', 'get', 200>>>,
  Assert<Conforms<PreviewResponse, Json<'/orders/preview', 'post', 200>>>,
  Assert<Conforms<PlaceOrderResponse, Json<'/orders', 'post', 201>>>,
  Assert<Conforms<{ orders: OrderDto[] }, Json<'/orders', 'get', 200>>>,
  Assert<Conforms<OrderDetail, Json<'/orders/{id}', 'get', 200>>>,
  Assert<Conforms<OrderDto, Json<'/orders/{id}', 'patch', 200>>>,
  Assert<Conforms<{ positions: PositionDto[] }, Json<'/positions', 'get', 200>>>,
  Assert<Conforms<{ fills: FillDto[] }, Json<'/fills', 'get', 200>>>,
  Assert<Conforms<AccountView, Json<'/accounts/me', 'get', 200>>>,
  Assert<Conforms<KillSwitchResponse, Json<'/kill-switch', 'post', 202>>>,
  Assert<Conforms<KillSwitchState, Json<'/kill-switch', 'get', 200>>>,
  Assert<Conforms<QuestionnaireResponse, Json<'/appropriateness/questionnaire', 'get', 200>>>,
];

// Negative control: the checker really rejects a drifted type.
type Drifted = Omit<OrderDto, 'filledQty'>;
export type NegativeControl = Assert<Conforms<Drifted, Json<'/orders/{id}', 'patch', 200>> extends false ? true : false>;

describe('SDK types conform to the OpenAPI contracts', () => {
  it('is checked at compile time (pnpm typecheck)', () => {
    const checks: ContractChecks | null = null;
    expect(checks).toBeNull();
  });
});
