packages:
  - "apps/*"
  - "packages/*"
  - "services/bot-runner"
  - "services/quant"

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - "@nestjs/core"
  - sharp

ignoredBuiltDependencies:
  - "@scarf/scarf"
  - protobufjs
