/* Generates src/styles/tokens.generated.css from src/tokens.ts, and dist/styles.css for consumers. */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { conventions, radii, space, themes, touchTarget, typography, type ThemeName } from '../src/tokens';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const kebab = (s: string) => s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);

export function tokensCss(): string {
  const out: string[] = ['/* GENERATED by scripts/build-css.ts from src/tokens.ts — do not edit. */'];
  out.push(':root {');
  for (const [k, v] of Object.entries(radii)) out.push(`  --k-radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(space)) out.push(`  --k-space-${k}: ${v};`);
  out.push('}');
  for (const name of Object.keys(themes) as ThemeName[]) {
    const sel = name === 'pro-dark' ? `:root, [data-theme='pro-dark']` : `[data-theme='novice-light']`;
    out.push(`${sel} {`);
    out.push(`  color-scheme: ${name === 'pro-dark' ? 'dark' : 'light'};`);
    for (const [k, v] of Object.entries(themes[name])) out.push(`  --k-${kebab(k)}: ${v};`);
    for (const [k, v] of Object.entries(typography[name])) out.push(`  --k-font-${k}: ${v};`);
    out.push(`  --k-touch: ${name === 'pro-dark' ? touchTarget.pro : touchTarget.novice};`);
    out.push('}');
    for (const [conv, c] of Object.entries(conventions[name])) {
      if (conv === 'blue_orange') continue;
      out.push(`[data-theme='${name}'][data-colors='${conv}'], [data-theme='${name}'] [data-colors='${conv}'] {`);
      out.push(`  --k-up: ${c.up};`);
      out.push(`  --k-down: ${c.down};`);
      out.push(`  --k-up-surface: ${c.upSurface};`);
      out.push(`  --k-down-surface: ${c.downSurface};`);
      out.push('}');
    }
  }
  return `${out.join('\n')}\n`;
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const tokens = tokensCss();
  writeFileSync(resolve(root, 'src/styles/tokens.generated.css'), tokens);
  if (process.argv.includes('--dist')) {
    mkdirSync(resolve(root, 'dist'), { recursive: true });
    const primitives = readFileSync(resolve(root, 'src/styles/primitives.css'), 'utf8');
    writeFileSync(resolve(root, 'dist/styles.css'), `${tokens}\n${primitives}`);
    writeFileSync(resolve(root, 'dist/tokens.css'), tokens);
  }
  console.warn('[ui] css generated');
}
