import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { en } from './en';
import { fr } from './fr';
import {
  clean,
  fkGrade,
  isProse,
  kandelMoles,
  stats,
  sum,
  syllablesEn,
  syllablesFr,
} from './readability';

const REPORT = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../../../../docs/novice/readability-report.md',
);
/** Goal 08 §9: grade 8 or lower for the whole corpus and for every longer string. */
const MAX_GRADE = 8;
const LONG = 12;

const rows = Object.entries(en)
  .filter(([k, v]) => isProse(k, v))
  .map(([k, v]) => {
    const s = stats(v, syllablesEn);
    const f = stats(fr[k as keyof typeof fr], syllablesFr);
    return { key: k, words: s.words, grade: fkGrade(s), fr: kandelMoles(f), s, f };
  });
const corpus = sum(rows.map((r) => r.s));
const corpusFr = sum(rows.map((r) => r.f));
const longCorpus = sum(rows.filter((r) => r.words >= LONG).map((r) => r.s));

describe('readability of the Novice copy', () => {
  it('syllable and grade heuristics behave on known words', () => {
    expect(syllablesEn('trade')).toBe(1);
    expect(syllablesEn('money')).toBe(2);
    expect(syllablesEn('automatically')).toBeGreaterThanOrEqual(5);
    expect(syllablesFr('maison')).toBe(2);
    expect(clean('A [safety net](term:safety-net) of **{amount}**.')).toBe('A safety net of it.');
    expect(fkGrade(stats('The cat sat on the mat.', syllablesEn))).toBeLessThan(2);
  });

  it(`the English corpus is at grade ${MAX_GRADE} or lower, and so is every string of ${LONG}+ words`, () => {
    expect(fkGrade(corpus)).toBeLessThanOrEqual(MAX_GRADE);
    expect(fkGrade(longCorpus)).toBeLessThanOrEqual(MAX_GRADE);
    const hard = rows
      .filter((r) => r.words >= LONG && r.grade > MAX_GRADE)
      .map((r) => `${r.key}: ${r.grade.toFixed(1)}`);
    expect(hard).toEqual([]);
  });

  it('writes docs/novice/readability-report.md when KORA_WRITE_READABILITY=1', () => {
    if (process.env.KORA_WRITE_READABILITY !== '1') return;
    const lines = [
      '# Novice copy readability report',
      '',
      'Generated by `pnpm --filter @kora/web readability` from `apps/web/src/lib/i18n/en.ts` and `fr.ts` (goal 08 §9).',
      'Markup and `{variables}` are stripped; labels and names under four words are left out.',
      '',
      `- English, Flesch–Kincaid grade (target ≤ ${MAX_GRADE}): **${fkGrade(corpus).toFixed(1)}** over ${rows.length} strings, ${corpus.words} words, ${corpus.sentences} sentences.`,
      `- English, grade over the ${rows.filter((r) => r.words >= LONG).length} longer strings only (${LONG}+ words, the paragraphs people actually read): **${fkGrade(longCorpus).toFixed(1)}**.`,
      `- Strings of ${LONG}+ words above grade ${MAX_GRADE}: **${rows.filter((r) => r.words >= LONG && r.grade > MAX_GRADE).length}** (highest: ${Math.max(...rows.filter((r) => r.words >= LONG).map((r) => r.grade)).toFixed(1)}).`,
      `- French, Kandel–Moles reading ease (information only; 60–70 ≈ plain language, higher is easier): **${kandelMoles(corpusFr).toFixed(0)}**.`,
      '',
      'Heuristic syllable counts; a human plain-language review (S1 + S8, B-504) is still owed: see `docs/novice/copy-review.md`.',
      '',
      '| Key | Words | EN grade | FR ease |',
      '|---|---:|---:|---:|',
      ...rows.map(
        (r) => `| \`${r.key}\` | ${r.words} | ${r.grade.toFixed(1)} | ${r.fr.toFixed(0)} |`,
      ),
      '',
    ];
    mkdirSync(dirname(REPORT), { recursive: true });
    writeFileSync(REPORT, lines.join('\n'));
  });
});
